### ISSUE TITLE
svgo is outdated

### ISSUE THREAD

**Issue by kumy** [nicolasbrugneaux/s3-bucket-svg-optimizer#1]
The current svgo version is `1.3.2 / 30.10.2019`, 0.6.1 is quite outdated :)

**Comment by nicolasbrugneaux** [comment]
You're not wrong. I just upgraded the dependencies. :)
That being said, I haven't this script in forever, if you want to use it
via `npx` (or similar), I could find some time tomorrow or next week to
make it happen.

**Comment by kumy** [comment]
Thanks, not sure if I will use this project or implement something similar in my project or anything else, as I also need to post-process other files formats. In any case, you had a good idea, and your project appeared first where I searched something doing that :+1:
